create database QuanLyNhanSu
GO
USE QuanLyNhanSu
GO
CREATE TABLE CHUCVU(
	MaCV VARCHAR(10) primary key,
	TenCV nvarchar(50)
)
GO

GO
CREATE TABLE PHONGBAN(
	MaPB VARCHAR(10) primary key,
	TenPB nvarchar(50),
	MaTP VARCHAR(10),
	DiaChi nvarchar(50),
	SDT char(15)
)

GO
create table TRINHDOHOCVAN(
	MaTDHV VARCHAR(10) primary key,
	TenTrinhDo nvarchar(50),
	ChuyenNganh nvarchar(50)
)

go
CREATE TABLE NHANVIEN(
	MaNV varchar(10) primary key,
	HoTen nvarchar(50),
	GioiTinh NVARCHAR(3),
	SDT CHAR(15),
	QueQuan nvarchar(50),
	NgaySinh date,
	MaTDHV VARCHAR(10) REFERENCES TrinhDoHocVan(MaTDHV),
	MaPB VARCHAR(10) references PhongBan(MaPB),
)

GO
CREATE TABLE NHANVIEN_CHUCVU(
	MaNV VARCHAR(10) REFERENCES NHANVIEN(MaNV),
	MaCV VARCHAR(10) REFERENCES CHUCVU(MaCV),
	PRIMARY KEY (MaNV,MaCV)
)
GO
CREATE TABLE HOPDONGLAODONG(
	MaHD VARCHAR(10) PRIMARY KEY,
	LoaiHD NVARCHAR(30),
	LuongThoaThuan BIGINT,
	MaNV VARCHAR(10) UNIQUE REFERENCES NHANVIEN(MaNV)
)
GO
CREATE TABLE DANGNHAP
(
	TaiKhoan NVARCHAR(30),
	MatKhau VARCHAR(30)
)
GO
CREATE PROC ThemPB(@MaPB VARCHAR(10),@TenPB NVARCHAR(50),@MaTP VARCHAR(10),@DiaChi NVARCHAR(50),@SDT CHAR(15)) AS
BEGIN
	 INSERT INTO PHONGBAN
	 VALUES  (@MaPB,@TenPB,@MaTP,@DiaChi,@SDT) 
END
go

CREATE PROC SuaPB (@MaPB VARCHAR(10),@TenPB NVARCHAR(50),@MaTP VARCHAR(10),@DiaChi NVARCHAR(50),@SDT CHAR(15)) AS
BEGIN
	UPDATE PHONGBAN SET 
	TenPB=@TenPB,MaTP=@MaTP,DiaChi=@DiaChi,SDT=@SDT	 
	WHERE MaPB=@MaPB
END
GO
CREATE PROC XoaPB(@MaPB VARCHAR(10)) AS
 BEGIN
		DELETE FROM PHONGBAN WHERE MaPB=@MaPB
 END
go
CREATE PROC ThemHD(@MaHD VARCHAR(10),@LoaiHD NVARCHAR(30),@Luongthoathuan BIGINT,@MaNV VARCHAR(10)) AS
BEGIN
	 INSERT INTO HOPDONGLAODONG
	 VALUES  (@MaHD,@LoaiHD,@Luongthoathuan,@MaNV) 
END
go

CREATE PROC SuaHD(@MaHD VARCHAR(10),@LoaiHD NVARCHAR(30),@Luongthoathuan BIGINT,@MaNV VARCHAR(10)) AS
BEGIN
	UPDATE HOPDONGLAODONG SET 
	LoaiHD=@LoaiHD,LuongThoaThuan=@Luongthoathuan,MaNV=@MaNV	 
	WHERE MaHD=@MaHD
END
GO
CREATE PROC XoaHD(@MaHD VARCHAR(10)) AS
 BEGIN
		DELETE FROM HOPDONGLAODONG WHERE MaHD=@MaHD
 END


 